let allElements = {
  1: {
    melting: 13.99,
    boiling: 20.271,
    year_discovered: "1766",
    density: 0.08988,
    electronegativity: 2.2,
    phase: "Gas",
    period: 1,
    name: "Hydrogen",
    symbol: "H",
    mass: "1.008",
    electronic_configuration: "1s¹",
    atomic_radius: "53 pm",
    group: 1,
    block: "s",
    category: "Reactive Nonmetal",
  },
  2: {
    melting: 0.95,
    boiling: 4.222,
    year_discovered: "1868",
    density: 0.1786,
    electronegativity: null,
    phase: "Gas",
    period: 1,
    name: "Helium",
    symbol: "He",
    mass: "4.0026",
    electronic_configuration: "1s²",
    atomic_radius: "31 pm",
    group: 18,
    block: "s",
    category: "Noble Gas",
  },
  3: {
    melting: 453.65,
    boiling: 1603,
    year_discovered: "1817",
    density: 0.534,
    electronegativity: 0.98,
    phase: "Solid",
    period: 2,
    name: "Lithium",
    symbol: "Li",
    mass: "6.94",
    electronic_configuration: "[He] 2s¹",
    atomic_radius: "167 pm",
    group: 1,
    block: "s",
    category: "Alkali Metal",
  },
  4: {
    melting: 1560,
    boiling: 2742,
    year_discovered: "1798",
    density: 1.85,
    electronegativity: 1.57,
    phase: "Solid",
    period: 2,
    name: "Beryllium",
    symbol: "Be",
    mass: "9.0122",
    electronic_configuration: "[He] 2s²",
    atomic_radius: "112 pm",
    group: 2,
    block: "s",
    category: "Alkaline Earth Metal",
  },
  5: {
    melting: 2349,
    boiling: 4200,
    year_discovered: "1808",
    density: 2.34,
    electronegativity: 2.04,
    phase: "Solid",
    period: 2,
    name: "Boron",
    symbol: "B",
    mass: "10.81",
    electronic_configuration: "[He] 2s² 2p¹",
    atomic_radius: "87 pm",
    group: 13,
    block: "p",
    category: "Metalloid",
  },
  6: {
    melting: 3800,
    boiling: 4300,
    year_discovered: "Ancient",
    density: 2.267,
    electronegativity: 2.55,
    phase: "Solid",
    period: 2,
    name: "Carbon",
    symbol: "C",
    mass: "12.011",
    electronic_configuration: "[He] 2s² 2p²",
    atomic_radius: "67 pm",
    group: 14,
    block: "p",
    category: "Reactive Nonmetal",
  },
  7: {
    melting: 63.15,
    boiling: 77.36,
    year_discovered: "1772",
    density: 1.2506,
    electronegativity: 3.04,
    phase: "Gas",
    period: 2,
    name: "Nitrogen",
    symbol: "N",
    mass: "14.007",
    electronic_configuration: "[He] 2s² 2p³",
    atomic_radius: "56 pm",
    group: 15,
    block: "p",
    category: "Reactive Nonmetal",
  },
  8: {
    melting: 54.36,
    boiling: 90.2,
    year_discovered: "1774",
    density: 1.429,
    electronegativity: 3.44,
    phase: "Gas",
    period: 2,
    name: "Oxygen",
    symbol: "O",
    mass: "15.999",
    electronic_configuration: "[He] 2s² 2p⁴",
    atomic_radius: "48 pm",
    group: 16,
    block: "p",
    category: "Reactive Nonmetal",
  },
  9: {
    melting: 53.53,
    boiling: 85.03,
    year_discovered: "1886",
    density: 1.696,
    electronegativity: 3.98,
    phase: "Gas",
    period: 2,
    name: "Fluorine",
    symbol: "F",
    mass: "18.998",
    electronic_configuration: "[He] 2s² 2p⁵",
    atomic_radius: "42 pm",
    group: 17,
    block: "p",
    category: "Halogen",
  },
  10: {
    melting: 24.56,
    boiling: 27.07,
    year_discovered: "1898",
    density: 0.9002,
    electronegativity: null,
    phase: "Gas",
    period: 2,
    name: "Neon",
    symbol: "Ne",
    mass: "20.180",
    electronic_configuration: "[He] 2s² 2p⁶",
    atomic_radius: "38 pm",
    group: 18,
    block: "p",
    category: "Noble Gas",
  },
  11: {
    melting: 370.87,
    boiling: 1156,
    year_discovered: "1807",
    density: 0.968,
    electronegativity: 0.93,
    phase: "Solid",
    period: 3,
    name: "Sodium",
    symbol: "Na",
    mass: "22.990",
    electronic_configuration: "[Ne] 3s¹",
    atomic_radius: "190 pm",
    group: 1,
    block: "s",
    category: "Alkali Metal",
  },
  12: {
    melting: 923,
    boiling: 1363,
    year_discovered: "1808",
    density: 1.738,
    electronegativity: 1.31,
    phase: "Solid",
    period: 3,
    name: "Magnesium",
    symbol: "Mg",
    mass: "24.305",
    electronic_configuration: "[Ne] 3s²",
    atomic_radius: "145 pm",
    group: 2,
    block: "s",
    category: "Alkaline Earth Metal",
  },
  13: {
    melting: 933.47,
    boiling: 2792,
    year_discovered: "1825",
    density: 2.7,
    electronegativity: 1.61,
    phase: "Solid",
    period: 3,
    name: "Aluminum",
    symbol: "Al",
    mass: "26.982",
    electronic_configuration: "[Ne] 3s² 3p¹",
    atomic_radius: "118 pm",
    group: 13,
    block: "p",
    category: "Post-transition Metal",
  },
  14: {
    melting: 1687,
    boiling: 3538,
    year_discovered: "1824",
    density: 2.329,
    electronegativity: 1.9,
    phase: "Solid",
    period: 3,
    name: "Silicon",
    symbol: "Si",
    mass: "28.085",
    electronic_configuration: "[Ne] 3s² 3p²",
    atomic_radius: "111 pm",
    group: 14,
    block: "p",
    category: "Metalloid",
  },
  15: {
    melting: 317.3,
    boiling: 550,
    year_discovered: "1669",
    density: 1.823,
    electronegativity: 2.19,
    phase: "Solid",
    period: 3,
    name: "Phosphorus",
    symbol: "P",
    mass: "30.974",
    electronic_configuration: "[Ne] 3s² 3p³",
    atomic_radius: "106 pm",
    group: 15,
    block: "p",
    category: "Reactive Nonmetal",
  },
  16: {
    melting: 388.36,
    boiling: 717.8,
    year_discovered: "Ancient",
    density: 2.07,
    electronegativity: 2.58,
    phase: "Solid",
    period: 3,
    name: "Sulfur",
    symbol: "S",
    mass: "32.06",
    electronic_configuration: "[Ne] 3s² 3p⁴",
    atomic_radius: "102 pm",
    group: 16,
    block: "p",
    category: "Reactive Nonmetal",
  },
  17: {
    melting: 171.6,
    boiling: 239.11,
    year_discovered: "1774",
    density: 3.2,
    electronegativity: 3.16,
    phase: "Gas",
    period: 3,
    name: "Chlorine",
    symbol: "Cl",
    mass: "35.45",
    electronic_configuration: "[Ne] 3s² 3p⁵",
    atomic_radius: "99 pm",
    group: 17,
    block: "p",
    category: "Halogen",
  },
  18: {
    melting: 83.8,
    boiling: 87.3,
    year_discovered: "1894",
    density: 1.784,
    electronegativity: null,
    phase: "Gas",
    period: 3,
    name: "Argon",
    symbol: "Ar",
    mass: "39.948",
    electronic_configuration: "[Ne] 3s² 3p⁶",
    atomic_radius: "97 pm",
    group: 18,
    block: "p",
    category: "Noble Gas",
  },
  19: {
    melting: 336.53,
    boiling: 1032,
    year_discovered: "1807",
    density: 0.862,
    electronegativity: 0.82,
    phase: "Solid",
    period: 4,
    name: "Potassium",
    symbol: "K",
    mass: "39.098",
    electronic_configuration: "[Ar] 4s¹",
    atomic_radius: "243 pm",
    group: 1,
    block: "s",
    category: "Alkali Metal",
  },
  20: {
    melting: 1115,
    boiling: 1757,
    year_discovered: "1808",
    density: 1.55,
    electronegativity: 1,
    phase: "Solid",
    period: 4,
    name: "Calcium",
    symbol: "Ca",
    mass: "40.078",
    electronic_configuration: "[Ar] 4s²",
    atomic_radius: "194 pm",
    group: 2,
    block: "s",
    category: "Alkaline Earth Metal",
  },
  21: {
    melting: 1814,
    boiling: 3109,
    year_discovered: "1879",
    density: 2.985,
    electronegativity: 1.36,
    phase: "Solid",
    period: 4,
    name: "Scandium",
    symbol: "Sc",
    mass: "44.956",
    electronic_configuration: "[Ar] 3d¹ 4s²",
    atomic_radius: "162 pm",
    group: 3,
    block: "d",
    category: "Transition Metal",
  },
  22: {
    melting: 1941,
    boiling: 3560,
    year_discovered: "1791",
    density: 4.506,
    electronegativity: 1.54,
    phase: "Solid",
    period: 4,
    name: "Titanium",
    symbol: "Ti",
    mass: "47.867",
    electronic_configuration: "[Ar] 3d² 4s²",
    atomic_radius: "147 pm",
    group: 4,
    block: "d",
    category: "Transition Metal",
  },
  23: {
    melting: 2183,
    boiling: 3680,
    year_discovered: "1801",
    density: 6.11,
    electronegativity: 1.63,
    phase: "Solid",
    period: 4,
    name: "Vanadium",
    symbol: "V",
    mass: "50.942",
    electronic_configuration: "[Ar] 3d³ 4s²",
    atomic_radius: "134 pm",
    group: 5,
    block: "d",
    category: "Transition Metal",
  },
  24: {
    melting: 2180,
    boiling: 2944,
    year_discovered: "1797",
    density: 7.19,
    electronegativity: 1.66,
    phase: "Solid",
    period: 4,
    name: "Chromium",
    symbol: "Cr",
    mass: "51.996",
    electronic_configuration: "[Ar] 3d⁵ 4s¹",
    atomic_radius: "127 pm",
    group: 6,
    block: "d",
    category: "Transition Metal",
  },
  25: {
    melting: 1519,
    boiling: 2334,
    year_discovered: "1774",
    density: 7.21,
    electronegativity: 1.55,
    phase: "Solid",
    period: 4,
    name: "Manganese",
    symbol: "Mn",
    mass: "54.938",
    electronic_configuration: "[Ar] 3d⁵ 4s²",
    atomic_radius: "139 pm",
    group: 7,
    block: "d",
    category: "Transition Metal",
  },
  26: {
    melting: 1811,
    boiling: 3134,
    year_discovered: "Ancient",
    density: 7.874,
    electronegativity: 1.83,
    phase: "Solid",
    period: 4,
    name: "Iron",
    symbol: "Fe",
    mass: "55.845",
    electronic_configuration: "[Ar] 3d⁶ 4s²",
    atomic_radius: "126 pm",
    group: 8,
    block: "d",
    category: "Transition Metal",
  },
  27: {
    melting: 1768,
    boiling: 3200,
    year_discovered: "1735",
    density: 8.9,
    electronegativity: 1.88,
    phase: "Solid",
    period: 4,
    name: "Cobalt",
    symbol: "Co",
    mass: "58.933",
    electronic_configuration: "[Ar] 3d⁷ 4s²",
    atomic_radius: "125 pm",
    group: 9,
    block: "d",
    category: "Transition Metal",
  },
  28: {
    melting: 1728,
    boiling: 3186,
    year_discovered: "1751",
    density: 8.908,
    electronegativity: 1.91,
    phase: "Solid",
    period: 4,
    name: "Nickel",
    symbol: "Ni",
    mass: "58.693",
    electronic_configuration: "[Ar] 3d⁸ 4s²",
    atomic_radius: "124 pm",
    group: 10,
    block: "d",
    category: "Transition Metal",
  },
  29: {
    melting: 1357.77,
    boiling: 2835,
    year_discovered: "Ancient",
    density: 8.96,
    electronegativity: 1.9,
    phase: "Solid",
    period: 4,
    name: "Copper",
    symbol: "Cu",
    mass: "63.546",
    electronic_configuration: "[Ar] 3d¹⁰ 4s¹",
    atomic_radius: "128 pm",
    group: 11,
    block: "d",
    category: "Transition Metal",
  },
  30: {
    melting: 692.68,
    boiling: 1180,
    year_discovered: "1746",
    density: 7.14,
    electronegativity: 1.65,
    phase: "Solid",
    period: 4,
    name: "Zinc",
    symbol: "Zn",
    mass: "65.38",
    electronic_configuration: "[Ar] 3d¹⁰ 4s²",
    atomic_radius: "134 pm",
    group: 12,
    block: "d",
    category: "Transition Metal",
  },
  31: {
    melting: 302.91,
    boiling: 2477,
    year_discovered: "1875",
    density: 5.91,
    electronegativity: 1.81,
    phase: "Solid",
    period: 4,
    name: "Gallium",
    symbol: "Ga",
    mass: "69.723",
    electronic_configuration: "[Ar] 3d¹⁰ 4s² 4p¹",
    atomic_radius: "135 pm",
    group: 13,
    block: "p",
    category: "Post-transition Metal",
  },
  32: {
    melting: 1211.4,
    boiling: 3106,
    year_discovered: "1886",
    density: 5.323,
    electronegativity: 2.01,
    phase: "Solid",
    period: 4,
    name: "Germanium",
    symbol: "Ge",
    mass: "72.630",
    electronic_configuration: "[Ar] 3d¹⁰ 4s² 4p²",
    atomic_radius: "122 pm",
    group: 14,
    block: "p",
    category: "Metalloid",
  },
  33: {
    melting: 1090,
    boiling: 887,
    year_discovered: "Ancient",
    density: 5.727,
    electronegativity: 2.18,
    phase: "Solid",
    period: 4,
    name: "Arsenic",
    symbol: "As",
    mass: "74.922",
    electronic_configuration: "[Ar] 3d¹⁰ 4s² 4p³",
    atomic_radius: "114 pm",
    group: 15,
    block: "p",
    category: "Metalloid",
  },
  34: {
    melting: 494,
    boiling: 958,
    year_discovered: "1817",
    density: 4.81,
    electronegativity: 2.55,
    phase: "Solid",
    period: 4,
    name: "Selenium",
    symbol: "Se",
    mass: "78.971",
    electronic_configuration: "[Ar] 3d¹⁰ 4s² 4p⁴",
    atomic_radius: "103 pm",
    group: 16,
    block: "p",
    category: "Reactive Nonmetal",
  },
  35: {
    melting: 265.8,
    boiling: 332,
    year_discovered: "1826",
    density: 3.1028,
    electronegativity: 2.96,
    phase: "Liquid",
    period: 4,
    name: "Bromine",
    symbol: "Br",
    mass: "79.904",
    electronic_configuration: "[Ar] 3d¹⁰ 4s² 4p⁵",
    atomic_radius: "94 pm",
    group: 17,
    block: "p",
    category: "Halogen",
  },
  36: {
    melting: 115.79,
    boiling: 119.93,
    year_discovered: "1898",
    density: 3.749,
    electronegativity: 3,
    phase: "Gas",
    period: 4,
    name: "Krypton",
    symbol: "Kr",
    mass: "83.798",
    electronic_configuration: "[Ar] 3d¹⁰ 4s² 4p⁶",
    atomic_radius: "88 pm",
    group: 18,
    block: "p",
    category: "Noble Gas",
  },
  37: {
    melting: 312.46,
    boiling: 961,
    year_discovered: "1861",
    density: 1.532,
    electronegativity: 0.82,
    phase: "Solid",
    period: 5,
    name: "Rubidium",
    symbol: "Rb",
    mass: "85.468",
    electronic_configuration: "[Kr] 5s¹",
    atomic_radius: "265 pm",
    group: 1,
    block: "s",
    category: "Alkali Metal",
  },
  38: {
    melting: 1050,
    boiling: 1655,
    year_discovered: "1790",
    density: 2.64,
    electronegativity: 0.95,
    phase: "Solid",
    period: 5,
    name: "Strontium",
    symbol: "Sr",
    mass: "87.62",
    electronic_configuration: "[Kr] 5s²",
    atomic_radius: "219 pm",
    group: 2,
    block: "s",
    category: "Alkaline Earth Metal",
  },
  39: {
    melting: 1799,
    boiling: 3609,
    year_discovered: "1794",
    density: 4.472,
    electronegativity: 1.22,
    phase: "Solid",
    period: 5,
    name: "Yttrium",
    symbol: "Y",
    mass: "88.906",
    electronic_configuration: "[Kr] 4d¹ 5s²",
    atomic_radius: "190 pm",
    group: 3,
    block: "d",
    category: "Transition Metal",
  },
  40: {
    melting: 2128,
    boiling: 4682,
    year_discovered: "1789",
    density: 6.52,
    electronegativity: 1.33,
    phase: "Solid",
    period: 5,
    name: "Zirconium",
    symbol: "Zr",
    mass: "91.224",
    electronic_configuration: "[Kr] 4d² 5s²",
    atomic_radius: "175 pm",
    group: 4,
    block: "d",
    category: "Transition Metal",
  },
  41: {
    melting: 2750,
    boiling: 5017,
    year_discovered: "1801",
    density: 8.57,
    electronegativity: 1.6,
    phase: "Solid",
    period: 5,
    name: "Niobium",
    symbol: "Nb",
    mass: "92.906",
    electronic_configuration: "[Kr] 4d⁴ 5s¹",
    atomic_radius: "164 pm",
    group: 5,
    block: "d",
    category: "Transition Metal",
  },
  42: {
    melting: 2896,
    boiling: 4912,
    year_discovered: "1778",
    density: 10.28,
    electronegativity: 2.16,
    phase: "Solid",
    period: 5,
    name: "Molybdenum",
    symbol: "Mo",
    mass: "95.95",
    electronic_configuration: "[Kr] 4d⁵ 5s¹",
    atomic_radius: "154 pm",
    group: 6,
    block: "d",
    category: "Transition Metal",
  },
  43: {
    melting: 2430,
    boiling: 4538,
    year_discovered: "1937",
    density: 11,
    electronegativity: 1.9,
    phase: "Solid",
    period: 5,
    name: "Technetium",
    symbol: "Tc",
    mass: "98",
    electronic_configuration: "[Kr] 4d⁵ 5s²",
    atomic_radius: "147 pm",
    group: 7,
    block: "d",
    category: "Transition Metal",
  },
  44: {
    melting: 2607,
    boiling: 4423,
    year_discovered: "1844",
    density: 12.45,
    electronegativity: 2.2,
    phase: "Solid",
    period: 5,
    name: "Ruthenium",
    symbol: "Ru",
    mass: "101.07",
    electronic_configuration: "[Kr] 4d⁷ 5s¹",
    atomic_radius: "146 pm",
    group: 8,
    block: "d",
    category: "Transition Metal",
  },
  45: {
    melting: 2237,
    boiling: 3968,
    year_discovered: "1803",
    density: 12.41,
    electronegativity: 2.28,
    phase: "Solid",
    period: 5,
    name: "Rhodium",
    symbol: "Rh",
    mass: "102.91",
    electronic_configuration: "[Kr] 4d⁸ 5s¹",
    atomic_radius: "142 pm",
    group: 9,
    block: "d",
    category: "Transition Metal",
  },
  46: {
    melting: 1828.05,
    boiling: 3236,
    year_discovered: "1803",
    density: 12.023,
    electronegativity: 2.2,
    phase: "Solid",
    period: 5,
    name: "Palladium",
    symbol: "Pd",
    mass: "106.42",
    electronic_configuration: "[Kr] 4d¹⁰",
    atomic_radius: "139 pm",
    group: 10,
    block: "d",
    category: "Transition Metal",
  },
  47: {
    melting: 1234.93,
    boiling: 2435,
    year_discovered: "Ancient",
    density: 10.49,
    electronegativity: 1.93,
    phase: "Solid",
    period: 5,
    name: "Silver",
    symbol: "Ag",
    mass: "107.87",
    electronic_configuration: "[Kr] 4d¹⁰ 5s¹",
    atomic_radius: "145 pm",
    group: 11,
    block: "d",
    category: "Transition Metal",
  },
  48: {
    melting: 594.22,
    boiling: 1040,
    year_discovered: "1817",
    density: 8.65,
    electronegativity: 1.69,
    phase: "Solid",
    period: 5,
    name: "Cadmium",
    symbol: "Cd",
    mass: "112.41",
    electronic_configuration: "[Kr] 4d¹⁰ 5s²",
    atomic_radius: "144 pm",
    group: 12,
    block: "d",
    category: "Transition Metal",
  },
  49: {
    melting: 429.75,
    boiling: 2345,
    year_discovered: "1863",
    density: 7.31,
    electronegativity: 1.78,
    phase: "Solid",
    period: 5,
    name: "Indium",
    symbol: "In",
    mass: "114.82",
    electronic_configuration: "[Kr] 4d¹⁰ 5s² 5p¹",
    atomic_radius: "167 pm",
    group: 13,
    block: "p",
    category: "Post-transition Metal",
  },
  50: {
    melting: 505.08,
    boiling: 2875,
    year_discovered: "Ancient",
    density: 7.31,
    electronegativity: 1.96,
    phase: "Solid",
    period: 5,
    name: "Tin",
    symbol: "Sn",
    mass: "118.71",
    electronic_configuration: "[Kr] 4d¹⁰ 5s² 5p²",
    atomic_radius: "158 pm",
    group: 14,
    block: "p",
    category: "Post-transition Metal",
  },
  51: {
    melting: 903.78,
    boiling: 1860,
    year_discovered: "Ancient",
    density: 6.697,
    electronegativity: 2.05,
    phase: "Solid",
    period: 5,
    name: "Antimony",
    symbol: "Sb",
    mass: "121.76",
    electronic_configuration: "[Kr] 4d¹⁰ 5s² 5p³",
    atomic_radius: "140 pm",
    group: 15,
    block: "p",
    category: "Metalloid",
  },
  52: {
    melting: 722.66,
    boiling: 1261,
    year_discovered: "1782",
    density: 6.24,
    electronegativity: 2.1,
    phase: "Solid",
    period: 5,
    name: "Tellurium",
    symbol: "Te",
    mass: "127.60",
    electronic_configuration: "[Kr] 4d¹⁰ 5s² 5p⁴",
    atomic_radius: "123 pm",
    group: 16,
    block: "p",
    category: "Metalloid",
  },
  53: {
    melting: 386.85,
    boiling: 457.4,
    year_discovered: "1811",
    density: 4.933,
    electronegativity: 2.66,
    phase: "Solid",
    period: 5,
    name: "Iodine",
    symbol: "I",
    mass: "126.90",
    electronic_configuration: "[Kr] 4d¹⁰ 5s² 5p⁵",
    atomic_radius: "115 pm",
    group: 17,
    block: "p",
    category: "Halogen",
  },
  54: {
    melting: 161.4,
    boiling: 165.03,
    year_discovered: "1898",
    density: 5.894,
    electronegativity: 2.6,
    phase: "Gas",
    period: 5,
    name: "Xenon",
    symbol: "Xe",
    mass: "131.29",
    electronic_configuration: "[Kr] 4d¹⁰ 5s² 5p⁶",
    atomic_radius: "108 pm",
    group: 18,
    block: "p",
    category: "Noble Gas",
  },
  55: {
    melting: 301.59,
    boiling: 944,
    year_discovered: "1860",
    density: 1.93,
    electronegativity: 0.79,
    phase: "Solid",
    period: 6,
    name: "Cesium",
    symbol: "Cs",
    mass: "132.91",
    electronic_configuration: "[Xe] 6s¹",
    atomic_radius: "298 pm",
    group: 1,
    block: "s",
    category: "Alkali Metal",
  },
  56: {
    melting: 1000,
    boiling: 2170,
    year_discovered: "1808",
    density: 3.51,
    electronegativity: 0.89,
    phase: "Solid",
    period: 6,
    name: "Barium",
    symbol: "Ba",
    mass: "137.33",
    electronic_configuration: "[Xe] 6s²",
    atomic_radius: "222 pm",
    group: 2,
    block: "s",
    category: "Alkaline Earth Metal",
  },
  57: {
    melting: 1193,
    boiling: 3737,
    year_discovered: "1839",
    density: 6.162,
    electronegativity: 1.1,
    phase: "Solid",
    period: 6,
    name: "Lanthanum",
    symbol: "La",
    mass: "138.91",
    electronic_configuration: "[Xe] 5d¹ 6s²",
    atomic_radius: "195 pm",
    group: 3,
    block: "f",
    category: "Lanthanide",
  },
  58: {
    melting: 1068,
    boiling: 3716,
    year_discovered: "1803",
    density: 6.77,
    electronegativity: 1.12,
    phase: "Solid",
    period: 6,
    name: "Cerium",
    symbol: "Ce",
    mass: "140.12",
    electronic_configuration: "[Xe] 4f¹ 5d¹ 6s²",
    atomic_radius: "172 pm",
    group: 3,
    block: "f",
    category: "Lanthanide",
  },
  59: {
    melting: 1208,
    boiling: 3793,
    year_discovered: "1885",
    density: 6.77,
    electronegativity: 1.13,
    phase: "Solid",
    period: 6,
    name: "Praseodymium",
    symbol: "Pr",
    mass: "140.91",
    electronic_configuration: "[Xe] 4f³ 6s²",
    atomic_radius: "196 pm",
    group: 3,
    block: "f",
    category: "Lanthanide",
  },
  60: {
    melting: 1297,
    boiling: 3347,
    year_discovered: "1885",
    density: 7.01,
    electronegativity: 1.14,
    phase: "Solid",
    period: 6,
    name: "Neodymium",
    symbol: "Nd",
    mass: "144.24",
    electronic_configuration: "[Xe] 4f⁴ 6s²",
    atomic_radius: "181 pm",
    group: 3,
    block: "f",
    category: "Lanthanide",
  },
  61: {
    melting: 1315,
    boiling: 3273,
    year_discovered: "1945",
    density: 7.26,
    electronegativity: 1.13,
    phase: "Solid",
    period: 6,
    name: "Promethium",
    symbol: "Pm",
    mass: "145",
    electronic_configuration: "[Xe] 4f⁵ 6s²",
    atomic_radius: "183 pm",
    group: 3,
    block: "f",
    category: "Lanthanide",
  },
  62: {
    melting: 1345,
    boiling: 2067,
    year_discovered: "1879",
    density: 7.52,
    electronegativity: 1.17,
    phase: "Solid",
    period: 6,
    name: "Samarium",
    symbol: "Sm",
    mass: "150.36",
    electronic_configuration: "[Xe] 4f⁶ 6s²",
    atomic_radius: "180 pm",
    group: 3,
    block: "f",
    category: "Lanthanide",
  },
  63: {
    melting: 1099,
    boiling: 1802,
    year_discovered: "1901",
    density: 5.244,
    electronegativity: 1.2,
    phase: "Solid",
    period: 6,
    name: "Europium",
    symbol: "Eu",
    mass: "151.96",
    electronic_configuration: "[Xe] 4f⁷ 6s²",
    atomic_radius: "199 pm",
    group: 3,
    block: "f",
    category: "Lanthanide",
  },
  64: {
    melting: 1585,
    boiling: 3546,
    year_discovered: "1880",
    density: 7.9,
    electronegativity: 1.2,
    phase: "Solid",
    period: 6,
    name: "Gadolinium",
    symbol: "Gd",
    mass: "157.25",
    electronic_configuration: "[Xe] 4f⁷ 5d¹ 6s²",
    atomic_radius: "179 pm",
    group: 3,
    block: "f",
    category: "Lanthanide",
  },
  65: {
    melting: 1629,
    boiling: 3503,
    year_discovered: "1843",
    density: 8.23,
    electronegativity: 1.2,
    phase: "Solid",
    period: 6,
    name: "Terbium",
    symbol: "Tb",
    mass: "158.93",
    electronic_configuration: "[Xe] 4f⁹ 6s²",
    atomic_radius: "177 pm",
    group: 3,
    block: "f",
    category: "Lanthanide",
  },
  66: {
    melting: 1680,
    boiling: 2840,
    year_discovered: "1886",
    density: 8.54,
    electronegativity: 1.22,
    phase: "Solid",
    period: 6,
    name: "Dysprosium",
    symbol: "Dy",
    mass: "162.50",
    electronic_configuration: "[Xe] 4f¹⁰ 6s²",
    atomic_radius: "178 pm",
    group: 3,
    block: "f",
    category: "Lanthanide",
  },
  67: {
    melting: 1734,
    boiling: 2993,
    year_discovered: "1878",
    density: 8.79,
    electronegativity: 1.23,
    phase: "Solid",
    period: 6,
    name: "Holmium",
    symbol: "Ho",
    mass: "164.93",
    electronic_configuration: "[Xe] 4f¹¹ 6s²",
    atomic_radius: "176 pm",
    group: 3,
    block: "f",
    category: "Lanthanide",
  },
  68: {
    melting: 1802,
    boiling: 3141,
    year_discovered: "1843",
    density: 9.066,
    electronegativity: 1.24,
    phase: "Solid",
    period: 6,
    name: "Erbium",
    symbol: "Er",
    mass: "167.26",
    electronic_configuration: "[Xe] 4f¹² 6s²",
    atomic_radius: "176 pm",
    group: 3,
    block: "f",
    category: "Lanthanide",
  },
  69: {
    melting: 1818,
    boiling: 2223,
    year_discovered: "1879",
    density: 9.32,
    electronegativity: 1.25,
    phase: "Solid",
    period: 6,
    name: "Thulium",
    symbol: "Tm",
    mass: "168.93",
    electronic_configuration: "[Xe] 4f¹³ 6s²",
    atomic_radius: "175 pm",
    group: 3,
    block: "f",
    category: "Lanthanide",
  },
  70: {
    melting: 1097,
    boiling: 1469,
    year_discovered: "1878",
    density: 6.9,
    electronegativity: 1.1,
    phase: "Solid",
    period: 6,
    name: "Ytterbium",
    symbol: "Yb",
    mass: "173.05",
    electronic_configuration: "[Xe] 4f¹⁴ 6s²",
    atomic_radius: "194 pm",
    group: 3,
    block: "f",
    category: "Lanthanide",
  },
  71: {
    melting: 1925,
    boiling: 3675,
    year_discovered: "1907",
    density: 9.841,
    electronegativity: 1.27,
    phase: "Solid",
    period: 6,
    name: "Lutetium",
    symbol: "Lu",
    mass: "174.97",
    electronic_configuration: "[Xe] 4f¹⁴ 5d¹ 6s²",
    atomic_radius: "173 pm",
    group: 3,
    block: "d",
    category: "Lanthanide",
  },
  72: {
    melting: 2506,
    boiling: 4876,
    year_discovered: "1923",
    density: 13.31,
    electronegativity: 1.3,
    phase: "Solid",
    period: 6,
    name: "Hafnium",
    symbol: "Hf",
    mass: "178.49",
    electronic_configuration: "[Xe] 4f¹⁴ 5d² 6s²",
    atomic_radius: "159 pm",
    group: 4,
    block: "d",
    category: "Transition Metal",
  },
  73: {
    melting: 3290,
    boiling: 5731,
    year_discovered: "1802",
    density: 16.69,
    electronegativity: 1.5,
    phase: "Solid",
    period: 6,
    name: "Tantalum",
    symbol: "Ta",
    mass: "180.95",
    electronic_configuration: "[Xe] 4f¹⁴ 5d³ 6s²",
    atomic_radius: "149 pm",
    group: 5,
    block: "d",
    category: "Transition Metal",
  },
  74: {
    melting: 3695,
    boiling: 5828,
    year_discovered: "1783",
    density: 19.25,
    electronegativity: 2.36,
    phase: "Solid",
    period: 6,
    name: "Tungsten",
    symbol: "W",
    mass: "183.84",
    electronic_configuration: "[Xe] 4f¹⁴ 5d⁴ 6s²",
    atomic_radius: "141 pm",
    group: 6,
    block: "d",
    category: "Transition Metal",
  },
  75: {
    melting: 3459,
    boiling: 5869,
    year_discovered: "1925",
    density: 21.02,
    electronegativity: 1.9,
    phase: "Solid",
    period: 6,
    name: "Rhenium",
    symbol: "Re",
    mass: "186.21",
    electronic_configuration: "[Xe] 4f¹⁴ 5d⁵ 6s²",
    atomic_radius: "137 pm",
    group: 7,
    block: "d",
    category: "Transition Metal",
  },
  76: {
    melting: 3306,
    boiling: 5285,
    year_discovered: "1803",
    density: 22.59,
    electronegativity: 2.2,
    phase: "Solid",
    period: 6,
    name: "Osmium",
    symbol: "Os",
    mass: "190.23",
    electronic_configuration: "[Xe] 4f¹⁴ 5d⁶ 6s²",
    atomic_radius: "135 pm",
    group: 8,
    block: "d",
    category: "Transition Metal",
  },
  77: {
    melting: 2719,
    boiling: 4701,
    year_discovered: "1803",
    density: 22.56,
    electronegativity: 2.2,
    phase: "Solid",
    period: 6,
    name: "Iridium",
    symbol: "Ir",
    mass: "192.22",
    electronic_configuration: "[Xe] 4f¹⁴ 5d⁷ 6s²",
    atomic_radius: "136 pm",
    group: 9,
    block: "d",
    category: "Transition Metal",
  },
  78: {
    melting: 2041.4,
    boiling: 4098,
    year_discovered: "1735",
    density: 21.45,
    electronegativity: 2.28,
    phase: "Solid",
    period: 6,
    name: "Platinum",
    symbol: "Pt",
    mass: "195.08",
    electronic_configuration: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    atomic_radius: "139 pm",
    group: 10,
    block: "d",
    category: "Transition Metal",
  },
  79: {
    melting: 1337.33,
    boiling: 3129,
    year_discovered: "Ancient",
    density: 19.3,
    electronegativity: 2.54,
    phase: "Solid",
    period: 6,
    name: "Gold",
    symbol: "Au",
    mass: "196.97",
    electronic_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    atomic_radius: "144 pm",
    group: 11,
    block: "d",
    category: "Transition Metal",
  },
  80: {
    melting: 234.32,
    boiling: 629.88,
    year_discovered: "Ancient",
    density: 13.534,
    electronegativity: 2,
    phase: "Liquid",
    period: 6,
    name: "Mercury",
    symbol: "Hg",
    mass: "200.59",
    electronic_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    atomic_radius: "151 pm",
    group: 12,
    block: "d",
    category: "Transition Metal",
  },
  81: {
    melting: 577,
    boiling: 1746,
    year_discovered: "1861",
    density: 11.85,
    electronegativity: 1.62,
    phase: "Solid",
    period: 6,
    name: "Thallium",
    symbol: "Tl",
    mass: "204.38",
    electronic_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    atomic_radius: "148 pm",
    group: 13,
    block: "p",
    category: "Post-transition Metal",
  },
  82: {
    melting: 600.61,
    boiling: 2022,
    year_discovered: "Ancient",
    density: 11.34,
    electronegativity: 2.33,
    phase: "Solid",
    period: 6,
    name: "Lead",
    symbol: "Pb",
    mass: "207.2",
    electronic_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    atomic_radius: "147 pm",
    group: 14,
    block: "p",
    category: "Post-transition Metal",
  },
  83: {
    melting: 544.7,
    boiling: 1837,
    year_discovered: "1753",
    density: 9.78,
    electronegativity: 2.02,
    phase: "Solid",
    period: 6,
    name: "Bismuth",
    symbol: "Bi",
    mass: "208.98",
    electronic_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    atomic_radius: "146 pm",
    group: 15,
    block: "p",
    category: "Post-transition Metal",
  },
  84: {
    melting: 527,
    boiling: 1235,
    year_discovered: "1898",
    density: 9.196,
    electronegativity: 2,
    phase: "Solid",
    period: 6,
    name: "Polonium",
    symbol: "Po",
    mass: "209",
    electronic_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    atomic_radius: "167 pm",
    group: 16,
    block: "p",
    category: "Post-transition Metal",
  },
  85: {
    melting: 575,
    boiling: 610,
    year_discovered: "1940",
    density: null,
    electronegativity: 2.2,
    phase: "Solid",
    period: 6,
    name: "Astatine",
    symbol: "At",
    mass: "210",
    electronic_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    atomic_radius: "140 pm",
    group: 17,
    block: "p",
    category: "Metalloid",
  },
  86: {
    melting: 202,
    boiling: 211.3,
    year_discovered: "1900",
    density: 9.73,
    electronegativity: 2.2,
    phase: "Gas",
    period: 6,
    name: "Radon",
    symbol: "Rn",
    mass: "222",
    electronic_configuration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    atomic_radius: "145 pm",
    group: 18,
    block: "p",
    category: "Noble Gas",
  },
  87: {
    melting: 300,
    boiling: 950,
    year_discovered: "1939",
    density: 1.87,
    electronegativity: 0.7,
    phase: "Solid",
    period: 7,
    name: "Francium",
    symbol: "Fr",
    mass: "223",
    electronic_configuration: "[Rn] 7s¹",
    atomic_radius: "270 pm",
    group: 1,
    block: "s",
    category: "Alkali Metal",
  },
  88: {
    melting: 973,
    boiling: 2010,
    year_discovered: "1898",
    density: 5.5,
    electronegativity: 0.9,
    phase: "Solid",
    period: 7,
    name: "Radium",
    symbol: "Ra",
    mass: "226",
    electronic_configuration: "[Rn] 7s²",
    atomic_radius: "221 pm",
    group: 2,
    block: "s",
    category: "Alkaline Earth Metal",
  },
  89: {
    melting: 1323,
    boiling: 3471,
    year_discovered: "1899",
    density: 10.07,
    electronegativity: 1.1,
    phase: "Solid",
    period: 7,
    name: "Actinium",
    symbol: "Ac",
    mass: "227",
    electronic_configuration: "[Rn] 6d¹ 7s²",
    atomic_radius: "215 pm",
    group: 3,
    block: "f",
    category: "Actinide",
  },
  90: {
    melting: 2115,
    boiling: 5061,
    year_discovered: "1829",
    density: 11.72,
    electronegativity: 1.3,
    phase: "Solid",
    period: 7,
    name: "Thorium",
    symbol: "Th",
    mass: "232.04",
    electronic_configuration: "[Rn] 6d² 7s²",
    atomic_radius: "206 pm",
    group: 3,
    block: "f",
    category: "Actinide",
  },
  91: {
    melting: 1841,
    boiling: 4300,
    year_discovered: "1913",
    density: 15.37,
    electronegativity: 1.5,
    phase: "Solid",
    period: 7,
    name: "Protactinium",
    symbol: "Pa",
    mass: "231.04",
    electronic_configuration: "[Rn] 5f² 6d¹ 7s²",
    atomic_radius: "200 pm",
    group: 3,
    block: "f",
    category: "Actinide",
  },
  92: {
    melting: 1405.3,
    boiling: 4404,
    year_discovered: "1789",
    density: 18.95,
    electronegativity: 1.38,
    phase: "Solid",
    period: 7,
    name: "Uranium",
    symbol: "U",
    mass: "238.03",
    electronic_configuration: "[Rn] 5f³ 6d¹ 7s²",
    atomic_radius: "196 pm",
    group: 3,
    block: "f",
    category: "Actinide",
  },
  93: {
    melting: 917,
    boiling: 4273,
    year_discovered: "1940",
    density: 20.45,
    electronegativity: 1.36,
    phase: "Solid",
    period: 7,
    name: "Neptunium",
    symbol: "Np",
    mass: "237",
    electronic_configuration: "[Rn] 5f⁴ 6d¹ 7s²",
    atomic_radius: "190 pm",
    group: 3,
    block: "f",
    category: "Actinide",
  },
  94: {
    melting: 912.5,
    boiling: 3501,
    year_discovered: "1940",
    density: 19.816,
    electronegativity: 1.28,
    phase: "Solid",
    period: 7,
    name: "Plutonium",
    symbol: "Pu",
    mass: "244",
    electronic_configuration: "[Rn] 5f⁶ 7s²",
    atomic_radius: "187 pm",
    group: 3,
    block: "f",
    category: "Actinide",
  },
  95: {
    melting: 1449,
    boiling: 2880,
    year_discovered: "1944",
    density: 13.69,
    electronegativity: 1.3,
    phase: "Solid",
    period: 7,
    name: "Americium",
    symbol: "Am",
    mass: "243",
    electronic_configuration: "[Rn] 5f⁷ 7s²",
    atomic_radius: "180 pm",
    group: 3,
    block: "f",
    category: "Actinide",
  },
  96: {
    melting: 1613,
    boiling: 3383,
    year_discovered: "1944",
    density: 13.51,
    electronegativity: 1.3,
    phase: "Solid",
    period: 7,
    name: "Curium",
    symbol: "Cm",
    mass: "247",
    electronic_configuration: "[Rn] 5f⁷ 6d¹ 7s²",
    atomic_radius: "169 pm",
    group: 3,
    block: "f",
    category: "Actinide",
  },
  97: {
    melting: 1259,
    boiling: 2900,
    year_discovered: "1949",
    density: 14.78,
    electronegativity: 1.3,
    phase: "Solid",
    period: 7,
    name: "Berkelium",
    symbol: "Bk",
    mass: "247",
    electronic_configuration: "[Rn] 5f⁹ 7s²",
    atomic_radius: "170 pm",
    group: 3,
    block: "f",
    category: "Actinide",
  },
  98: {
    melting: 1173,
    boiling: 1743,
    year_discovered: "1950",
    density: 15.1,
    electronegativity: 1.3,
    phase: "Solid",
    period: 7,
    name: "Californium",
    symbol: "Cf",
    mass: "251",
    electronic_configuration: "[Rn] 5f¹⁰ 7s²",
    atomic_radius: "169 pm",
    group: 3,
    block: "f",
    category: "Actinide",
  },
  99: {
    melting: 1133,
    boiling: 1269,
    year_discovered: "1952",
    density: 8.84,
    electronegativity: 1.3,
    phase: "Solid",
    period: 7,
    name: "Einsteinium",
    symbol: "Es",
    mass: "252",
    electronic_configuration: "[Rn] 5f¹¹ 7s²",
    atomic_radius: "186 pm",
    group: 3,
    block: "f",
    category: "Actinide",
  },
  100: {
    melting: 1800,
    boiling: null,
    year_discovered: "1952",
    density: null,
    electronegativity: 1.3,
    phase: "Solid",
    period: 7,
    name: "Fermium",
    symbol: "Fm",
    mass: "257",
    electronic_configuration: "[Rn] 5f¹² 7s²",
    atomic_radius: "185 pm",
    group: 3,
    block: "f",
    category: "Actinide",
  },
  101: {
    melting: 1100,
    boiling: null,
    year_discovered: "1955",
    density: null,
    electronegativity: 1.3,
    phase: "Solid",
    period: 7,
    name: "Mendelevium",
    symbol: "Md",
    mass: "258",
    electronic_configuration: "[Rn] 5f¹³ 7s²",
    atomic_radius: "184 pm",
    group: 3,
    block: "f",
    category: "Actinide",
  },
  102: {
    melting: 1100,
    boiling: null,
    year_discovered: "1958",
    density: null,
    electronegativity: 1.3,
    phase: "Solid",
    period: 7,
    name: "Nobelium",
    symbol: "No",
    mass: "259",
    electronic_configuration: "[Rn] 5f¹⁴ 7s²",
    atomic_radius: "183 pm",
    group: 3,
    block: "f",
    category: "Actinide",
  },
  103: {
    melting: 1900,
    boiling: null,
    year_discovered: "1961",
    density: null,
    electronegativity: 1.3,
    phase: "Solid",
    period: 7,
    name: "Lawrencium",
    symbol: "Lr",
    mass: "266",
    electronic_configuration: "[Rn] 5f¹⁴ 7s² 7p¹",
    atomic_radius: "183 pm",
    group: 3,
    block: "d",
    category: "Actinide",
  },
  104: {
    melting: 2400,
    boiling: 5800,
    year_discovered: "1964",
    density: 23.2,
    electronegativity: null,
    phase: "Solid",
    period: 7,
    name: "Rutherfordium",
    symbol: "Rf",
    mass: "267",
    electronic_configuration: "[Rn] 5f¹⁴ 6d² 7s²",
    atomic_radius: "157 pm",
    group: 4,
    block: "d",
    category: "Transition Metal",
  },
  105: {
    melting: null,
    boiling: null,
    year_discovered: "1967",
    density: 29.3,
    electronegativity: null,
    phase: "Solid",
    period: 7,
    name: "Dubnium",
    symbol: "Db",
    mass: "268",
    electronic_configuration: "[Rn] 5f¹⁴ 6d³ 7s²",
    atomic_radius: "149 pm",
    group: 5,
    block: "d",
    category: "Transition Metal",
  },
  106: {
    melting: null,
    boiling: null,
    year_discovered: "1974",
    density: 35,
    electronegativity: null,
    phase: "Solid",
    period: 7,
    name: "Seaborgium",
    symbol: "Sg",
    mass: "269",
    electronic_configuration: "[Rn] 5f¹⁴ 6d⁴ 7s²",
    atomic_radius: "143 pm",
    group: 6,
    block: "d",
    category: "Transition Metal",
  },
  107: {
    melting: null,
    boiling: null,
    year_discovered: "1981",
    density: 37.1,
    electronegativity: null,
    phase: "Solid",
    period: 7,
    name: "Bohrium",
    symbol: "Bh",
    mass: "270",
    electronic_configuration: "[Rn] 5f¹⁴ 6d⁵ 7s²",
    atomic_radius: "141 pm",
    group: 7,
    block: "d",
    category: "Transition Metal",
  },
  108: {
    melting: null,
    boiling: null,
    year_discovered: "1984",
    density: 40.7,
    electronegativity: null,
    phase: "Solid",
    period: 7,
    name: "Hassium",
    symbol: "Hs",
    mass: "277",
    electronic_configuration: "[Rn] 5f¹⁴ 6d⁶ 7s²",
    atomic_radius: "134 pm",
    group: 8,
    block: "d",
    category: "Transition Metal",
  },
  109: {
    melting: null,
    boiling: null,
    year_discovered: "1982",
    density: 37.4,
    electronegativity: null,
    phase: "Solid",
    period: 7,
    name: "Meitnerium",
    symbol: "Mt",
    mass: "278",
    electronic_configuration: "[Rn] 5f¹⁴ 6d⁷ 7s²",
    atomic_radius: "129 pm",
    group: 9,
    block: "d",
    category: "Transition Metal",
  },
  110: {
    melting: null,
    boiling: null,
    year_discovered: "1994",
    density: 34.8,
    electronegativity: null,
    phase: "Solid",
    period: 7,
    name: "Darmstadtium",
    symbol: "Ds",
    mass: "281",
    electronic_configuration: "[Rn] 5f¹⁴ 6d⁸ 7s²",
    atomic_radius: "122 pm",
    group: 10,
    block: "d",
    category: "Transition Metal",
  },
  111: {
    melting: null,
    boiling: null,
    year_discovered: "1994",
    density: 28.7,
    electronegativity: null,
    phase: "Solid",
    period: 7,
    name: "Roentgenium",
    symbol: "Rg",
    mass: "282",
    electronic_configuration: "[Rn] 5f¹⁴ 6d⁹ 7s²",
    atomic_radius: "121 pm",
    group: 11,
    block: "d",
    category: "Transition Metal",
  },
  112: {
    melting: null,
    boiling: 357,
    year_discovered: "1996",
    density: 23.7,
    electronegativity: null,
    phase: "Gas",
    period: 7,
    name: "Copernicium",
    symbol: "Cn",
    mass: "285",
    electronic_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    atomic_radius: "145 pm",
    group: 12,
    block: "d",
    category: "Transition Metal",
  },
  113: {
    melting: 700,
    boiling: 1400,
    year_discovered: "2003",
    density: 16,
    electronegativity: null,
    phase: "Solid",
    period: 7,
    name: "Nihonium",
    symbol: "Nh",
    mass: "286",
    electronic_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    atomic_radius: "145 pm",
    group: 13,
    block: "p",
    category: "Post-transition Metal",
  },
  114: {
    melting: 340,
    boiling: 420,
    year_discovered: "1998",
    density: 14,
    electronegativity: null,
    phase: "Solid",
    period: 7,
    name: "Flerovium",
    symbol: "Fl",
    mass: "289",
    electronic_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    atomic_radius: "162 pm",
    group: 14,
    block: "p",
    category: "Post-transition Metal",
  },
  115: {
    melting: 670,
    boiling: 1400,
    year_discovered: "2003",
    density: 13.5,
    electronegativity: null,
    phase: "Solid",
    period: 7,
    name: "Moscovium",
    symbol: "Mc",
    mass: "290",
    electronic_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    atomic_radius: "150 pm",
    group: 15,
    block: "p",
    category: "Post-transition Metal",
  },
  116: {
    melting: 709,
    boiling: 1085,
    year_discovered: "2000",
    density: 12.9,
    electronegativity: null,
    phase: "Solid",
    period: 7,
    name: "Livermorium",
    symbol: "Lv",
    mass: "293",
    electronic_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    atomic_radius: "154 pm",
    group: 16,
    block: "p",
    category: "Post-transition Metal",
  },
  117: {
    melting: 723,
    boiling: 883,
    year_discovered: "2010",
    density: 7.2,
    electronegativity: null,
    phase: "Solid",
    period: 7,
    name: "Tennessine",
    symbol: "Ts",
    mass: "294",
    electronic_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    atomic_radius: "138 pm",
    group: 17,
    block: "p",
    category: "Halogen",
  },
  118: {
    melting: null,
    boiling: 350,
    year_discovered: "2002",
    density: 5,
    electronegativity: null,
    phase: "Gas",
    period: 7,
    name: "Oganesson",
    symbol: "Og",
    mass: "294",
    electronic_configuration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    atomic_radius: "152 pm",
    group: 18,
    block: "p",
    category: "Noble Gas",
  },
};

let table = document.getElementById("periodic-table");
let infoPanel = document.getElementById("info-panel");

let current_temperature = 298;
let temperature_input = document.getElementById("temperature-control-value");
temperature_input.addEventListener("input", () => {
  current_temperature = temperature_input.value;
  temperature_slider.value = current_temperature;
  updateElementState();
});
let temperature_slider = document.getElementById("temperature-slider");
temperature_slider.addEventListener("input", () => {
  current_temperature = temperature_slider.value;
  temperature_input.value = current_temperature;
  updateElementState();
});

function showInfo(atomic_number, element) {
  infoPanel.scrollIntoView();
  // header elements
  document.getElementById("atomic-number").textContent = atomic_number;
  document.getElementById("element-name").textContent = element.name;
  document.getElementById("electronic-configuration").textContent = element.electronic_configuration;
  // body elements
  document.getElementById("element-symbol-text").textContent = element.symbol;
  document.getElementById("atomic-radius-text").textContent = element.atomic_radius;
  document.getElementById("mass-number-text").textContent = `${element.mass} u`;
  document.getElementById("density-text").textContent = element.density;
  document.getElementById("electronegativity-text").textContent = element.electronegativity;
  document.getElementById("phase-text").textContent = element.phase;
  document.getElementById("period-text").textContent = element.period;
  document.getElementById("group-text").textContent = element.group;
  document.getElementById("block-text").textContent = element.block;
  document.getElementById("category-text").textContent = element.category;
  document.getElementById("year-discovered-text").textContent = element.year_discovered;
  document.getElementById("melting-point-text").textContent = element.melting;
  document.getElementById("boiling-point-text").textContent = element.boiling;
  document.getElementById("learn-more-link").href = `https://en.wikipedia.org/wiki/${element.name}`;
}

function updateElementState() {
  for (let atomic_number in allElements) {
    let element = allElements[atomic_number];
    let elementBtn = document.getElementById(element.symbol);
    elementBtn.classList.remove("state-Solid");
    elementBtn.classList.remove("state-Liquid");
    elementBtn.classList.remove("state-Gas");
    if (current_temperature < element.melting) {
      elementBtn.classList.add("state-Solid");
    } else if (current_temperature < element.boiling) {
      elementBtn.classList.add("state-Liquid");
    } else {
      elementBtn.classList.add("state-Gas");
    }
  }
}

function createElement(atomic_number, element) {
  let elementBtn = document.createElement("button");
  elementBtn.id = element.symbol;
  elementBtn.classList.add("by-state");
  elementBtn.classList.add("element-button");
  elementBtn.classList.add(`group-${element.group}`);
  elementBtn.classList.add(`period-${element.period}`);
  elementBtn.classList.add(`block-${element.block}`);
  elementBtn.classList.add(`state-${element.phase}`);
  elementBtn.classList.add(`category-${element.category.replace(/ /g, '-')}`);

  let div1 = document.createElement("div");
  div1.className = "element-info-div";
  // Atomic number
  let atomic_no_p = document.createElement("p");
  atomic_no_p.textContent = atomic_number;
  atomic_no_p.className = "atomic-number";
  div1.appendChild(atomic_no_p);
  elementBtn.appendChild(div1);

  let div2 = document.createElement("div");
  div2.className = "element-name-div";
  // Symbol
  let symbol_p = document.createElement("p");
  symbol_p.textContent = element.symbol;
  symbol_p.className = "element-symbol";
  div2.appendChild(symbol_p);
  // Name
  let name_p = document.createElement("p");
  name_p.textContent = element.name;
  name_p.className = "element-name";
  div2.appendChild(name_p);
  elementBtn.appendChild(div2);

  elementBtn.addEventListener("click", () => showInfo(atomic_number, element));

  return elementBtn;
}

for (let atomic_number in allElements) {
  let el = allElements[atomic_number];
  let parent;
  if (el.block == "f") {
    if (atomic_number > 88) {
      parent = document.getElementsByClassName(`period 7`)[0];
    } else {
      parent = document.getElementsByClassName(`period 6`)[0];
    }
  } else {
    parent = document.getElementsByClassName(`group ${el.group}`)[0];
  }

  parent.appendChild(createElement(atomic_number, el));
}

let viewModeSelect = document.getElementById("view-mode-select");
viewModeSelect.addEventListener("change", () => {
  table.classList.remove("by-state");
  table.classList.remove("by-block");
  table.classList.remove("by-category");
  table.classList.add(viewModeSelect.value);
  document.querySelectorAll(".color-relevance-div").forEach(div => {
    div.style.display = "none";
  });
  document.querySelectorAll(`.color-relevance-div.${viewModeSelect.value}`).forEach(div => {
    div.style.display = "flex";
  });
});

function checkOrientation() {
    if (document.body.offsetHeight > document.body.offsetWidth) {
        app.classList.remove("horizontal");
        app.classList.add("vertical");
    } else {
        app.classList.remove("vertical");
        app.classList.add("horizontal");
    }
}

window.addEventListener("resize", () => {
    checkOrientation();
});

window.addEventListener("DOMContentLoaded", () => {
    checkOrientation();
});