name: Pull Request Check

on:
  pull_request:
    paths:
      - "public/**/*"
      - "src/**/*"
      - "index.html"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
      - "eslint.config.js"
      - ".prettierrc"
      - "vite.config.ts"
      - ".github/workflows/*"

permissions:
  contents: read

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node v20
        uses: actions/setup-node@v7
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Project Dependencies
        run: npm ci

      - name: Format check
        run: npm run format:check

      - name: Lint check
        run: npm run lint:check

      - name: Build check
        run: npm run build
